ARG PARAM_REGISTRY
ARG PARAM_NAMESPACE
ARG PARAM_NAME
ARG PARAM_UBUNTU
ARG PARAM_MONGO

FROM alpine:latest
RUN echo ${PARAM_REGISTRY}/${PARAM_NAMESPACE}/${PARAM_NAME}:${PARAM_UBUNTU}-${PARAM_MONGO}

ARG TARGETARCH
RUN echo ${TARGETARCH} > /msg